"""set username to unique

Revision ID: 349e70448bf3
Revises: 7137d833bebf
Create Date: 2025-05-15 21:37:39.145559

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "349e70448bf3"
down_revision: Union[str, None] = "7137d833bebf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")  # type: ignore
    # ### end Alembic commands ###
